Traceback (most recent call last):
  File "main.py", line 301, in <module>
  File "main.py", line 198, in main
  File "socket.pyo", line 228, in meth
socket.error: [Errno 10051] 
Traceback (most recent call last):
  File "main.py", line 301, in <module>
  File "main.py", line 198, in main
  File "socket.pyo", line 228, in meth
socket.error: [Errno 10060] 
